version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports: 
      - 4306:3306
    networks:
      - webserver_stack
    volumes:
      - mycoolappvolume:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
  phpmyadmin:
    depends_on:
      - mariadb
    container_name: phpmyadmin
    image: phpmyadmin
    networks:
      - webserver_stack    
    ports: 
      - 8080:80
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 2000mb

volumes:
  mycoolappvolume:
networks:
  webserver_stack:

